title: "KEN's Atelier"
masthead_title: null 
logo: "/assets/images/logo.png" 

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme