title: "KEN's Atelier"
email: jungminna03@gmail.com
description: "Game Dev / Asset Discription / etc..."
# logo: "/assets/images/logo.png" 

# 주소 설정 (이게 중요합니다!)
baseurl: "" 
url: "http://localhost:4000"

# 플러그인
plugins:
  - jekyll-feed
  - jekyll-include-cache

# SCSS 설정
sass:
  sass_dir: _sass
  style: compressed